server:
  servlet:
    session:
      timeout: 168h
      cookie:
        name: lila-session
        http-only: true
        secure: true
  ssl:
    enabled: false
    key-store:
    store-type:
    key-store-password:
  port: 15342

spring:
  web:
    resources:
      static-locations: classpath:/static
  thymeleaf:
    cache: false
    prefix: classpath:/html/
  mvc:
    static-path-pattern: /static/**
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

lila:
  config:
